-- Catalog read-side schema: venues, events, shows, seats.
-- All PKs are UUIDs generated by the application (Java UUID.randomUUID()).

CREATE TABLE venues (
    id            UUID         PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    address       VARCHAR(500) NOT NULL,
    capacity      INTEGER      NOT NULL CHECK (capacity > 0),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_venues_name UNIQUE (name)
);

CREATE TABLE events (
    id            UUID         PRIMARY KEY,
    venue_id      UUID         NOT NULL REFERENCES venues(id),
    name          VARCHAR(200) NOT NULL,
    description   TEXT,
    status        VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_events_venue_name UNIQUE (venue_id, name),
    CONSTRAINT ck_events_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED'))
);

CREATE INDEX idx_events_venue_id ON events(venue_id);

CREATE TABLE shows (
    id            UUID         PRIMARY KEY,
    event_id      UUID         NOT NULL REFERENCES events(id),
    starts_at     TIMESTAMPTZ  NOT NULL,
    ends_at       TIMESTAMPTZ  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_shows_time CHECK (ends_at > starts_at),
    CONSTRAINT ck_shows_status CHECK (status IN ('SCHEDULED', 'CANCELLED', 'COMPLETED'))
);

CREATE INDEX idx_shows_event_id ON shows(event_id);
CREATE INDEX idx_shows_starts_at ON shows(starts_at);

CREATE TABLE seats (
    id            UUID         PRIMARY KEY,
    show_id       UUID         NOT NULL REFERENCES shows(id),
    section       VARCHAR(50)  NOT NULL,
    row_label     VARCHAR(10)  NOT NULL,
    seat_number   INTEGER      NOT NULL CHECK (seat_number > 0),
    price_cents   BIGINT       NOT NULL CHECK (price_cents >= 0),
    availability  VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_seats_position UNIQUE (show_id, section, row_label, seat_number),
    CONSTRAINT ck_seats_availability CHECK (availability IN ('AVAILABLE', 'HELD', 'BOOKED'))
);

CREATE INDEX idx_seats_show_id ON seats(show_id);
